#ifdef IMAGEPROCESSINGUTILS_EXPORTS
#define IMAGEPROCESSINGUTILS_API __declspec(dllexport)
#else
#define IMAGEPROCESSINGUTILS_API __declspec(dllimport)
#endif

enum IMAGEPROCESSINGUTILS_API revertable_options {
	CONFIDENCE,
	THRESHOLD,
	SHOW_FEATURES,
	FLIP_HORIZONTAL,
	FLIP_VERTICAL,
	SHOW_CONFIDENCE,
	BINARY_THRESHOLDING,
	ZERO_THRESHOLDING,
	TRUNC_THRESHOLDING,
	ADAPTIVE_THRESHOLDING,
	HISTOGRAM_EQUALIZATION,
	DETECT_EDGES,
	TRIANGLE_THRESHOLDING,
};